spring:
  application:
    name: ms-event-manager
  data:
    mongodb:
      uri: ${URI_DATA_BASE}
      database: db_event

server:
  port: 8080

ms:
  ticket:
    url:  ${MS_TICKET_URL:http://localhost:8081/api/v1/ticket}

feign:
  client:
    config:
      default:
        loggerLevel: full

springdoc:
  swagger-ui:
    path: /swagger-ms-event-manager.html
  api-docs:
    path: /docs-ms-event-manager
  packages-to-scan: com.anamariafelix.ms_event_manager.controller